canonical: https://gematik.de/fhir/ISiK/v2/testdaten
fhirVersion: 4.0.1
FSHOnly: true
name: Testdaten ISIK Stufe 2 2.0.0
status: active
dependencies:
  de.basisprofil.r4: 1.3.2
  de.gematik.isik-basismodul: 2.0.0-ballot3
  de.gematik.isik-vitalwerte: 2.0.0-ballot
  de.gematik.isik-basismodul-dokumentenaustausch: 2.0.0-ballot
  de.gematik.isik-medikation: 2.0.0-ballot
  hl7.fhir.r4.core: 4.0.1
  hl7.fhir.extensions.r5: 4.0.1
  dvmd.kdl.r4.2021: 2021.1.1
  ihe.mhd.fhir: 4.0.1
